### ISSUE TITLE
Even with both encryption and online login on...

### ISSUE THREAD

**Issue by wtfaremyinitials** [lukleh/TwistedBot#13]
Even with both encryption and online login on the terminal always says "USE ENCRYPTION IS FALSE, SKIPPING ENCRYPTION"....

**Comment by lukleh** [comment]
can you post the command with arguments that you are using?

**Comment by wtfaremyinitials** [comment]
$ python bot.py

**Comment by lukleh** [comment]
$ python bot.py -h to see the options...  then it should be clear what to use
