### ISSUE TITLE
Some Issues with 1.8

### ISSUE THREAD

**Issue by ghost** [lukleh/TwistedBot#16]
I can't seem to connect to 1.8.1 servers with this. It says something like "Cannot connect to %IP INSERTED HERE% Reason: Connection was ended cleanly." Also, I think the authentication has changed making the --onlinemode tag useless ATM either due to the new UUIDs or the fact they changed some links n' stuff. I am seeing how I can fix these issues manually, but for now, just wanted to make an official issue report.

**Comment by lukleh** [comment]
Hi, development stopped at "Support for Minecraft 1.5"
1.8.1 is already way too different....

focusing on a different project now

**Comment by ghost** [comment]
Ah, I had a feeling. Thanks though for making a cool piece of software.

**Comment by jonasrk** [comment]
Maybe look at https://github.com/nickelpro/spock

**Comment by ghost** [comment]
Thanks, that will help a lot!
