### ISSUE TITLE
[QUESTION] On login packet

### ISSUE THREAD

**Issue by FrederickGeek8** [lukleh/TwistedBot#3]
Is there some function somewhere in the code that will allow me to send a packet (using make_packet?) to the server once I have logged in?

Thanks

**Comment by lukleh** [comment]
There is a function to make/send packet in factory.MineCraftProtocol.send_packet(name, dict)
Right now there is a world.World.on_login function that gets called after receiving login packet, so for now you can your code there.
I am thinking about making a plugin/hooks infrastructure so people can hook up custom code without changing the core. So far I am way too busy with getting the bot to look for resources and dig :)

**Comment by FrederickGeek8** [comment]
Ooh sounds fun haha

What file is the world.World.on_login function in? I can't seem to find it...

**Comment by lukleh** [comment]
twistedbot/world.py

**Comment by FrederickGeek8** [comment]
How would I send a packet? So lets say I want to send packet 3 (0x03) with the field 'foo', how would I do that?

**Comment by lukleh** [comment]
world.World.send_packet("chat message", {"message":"foo})

so in world.World.on_login you do self.send_packet("chat message", {"message":"foo})

**Comment by lukleh** [comment]
if you are playing with the code, better pull the latest changes that I've just commited

**Comment by FrederickGeek8** [comment]
Thanks you :D I love playing around with this code :D
