### ISSUE TITLE
Proxy needs pycrypto module. [Documentation]

### ISSUE THREAD

**Issue by kurtismullins** [lukleh/TwistedBot#4]
In XUbuntu 12.10 I ran into an error while trying to run:

```
pypy ./proxy.py
```

It would return an error complaining about a missing Module (AES). After some quick searching, it turns out I needed to have the pycrypto module on my system.

Special note: After installing; I was still unable to get this to work with pypy. I had to resort to just using the standard CPython Interpreter:

```
python ./proxy.py
```

I believe this dependency should probably be mentioned in the documentation. Others running in to this problem may benefit by using CPython instead of pypy as well.

**Comment by lukleh** [comment]
Encryption is pain, but there is a way to run it under pypy.
The trick is not to use PyCrypto fastmath module. This can be achieved by changing PyCrypto setup.py
Try this:
on line 160 in setup.py add 

```
    self.__remove_extensions(["Crypto.PublicKey._fastmath"])
    return
```

and then install this patched version again.

The dependency is mentioned in the documentation:
"Optional (mandatory for proxy mode) PyCrypto dependency if you want the datastream to be encrypted. Configurable in config."
If it is not clear enough, I would welcome suggestions how to improve it.

**Comment by lukleh** [comment]
any progress on this?

**Comment by kurtismullins** [comment]
Hey,

I haven't had a chance to mess with this, yet. Sorry. Feel free to close. I'll review the documentation and what-not and submit a pull request if I think I can offer any help :)

Thanks!

**Comment by lukleh** [comment]
Ok, I am closing it for now. You can reopen later if relevant.
