### ISSUE TITLE
Not exactly an issue

### ISSUE THREAD

**Issue by wtfaremyinitials** [lukleh/TwistedBot#8]
Any chance you could add some short documentation about the "collect" and "drop" commands to the README.md? I have spent the last hour reading source code and have yet to figure out how to use the two. Thanks!

btw i changed my github username from minecrafttakeover to this.

**Comment by lukleh** [comment]
Hi, "drop" should probably be in readme. "collect" is jsut a sketch, so that better be not mentioned because it does not really works. There is also new command "help", I will update the readme.

**Comment by lukleh** [comment]
check the last commit and let me know if it works for you.
