### ISSUE TITLE
Some sort of chat filter?

### ISSUE THREAD

**Issue by vgel** [lukleh/TwistedBot#9]
I want to use this on a real server and to do that, I don't want messages spamming up global chat. It would be nice to be able to install (via code) some sort of ChatFilter class where you could redirect chat messages to be `/tell [Players] msg`.

I've already forked the repository for some other things, so if this would be useful to the main repo I'll code it and make a pull request.

**Comment by lukleh** [comment]
Set the WHISPER option in config to True. What is missing is a command line option to turn this on/off
